# Generated by Django 4.2 on 2023-04-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
