# Generated by Django 4.2 on 2023-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0003_remove_word_example_word_example_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.URLField(blank=True),
        ),
    ]
