# Generated by Django 4.2 on 2023-04-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0004_alter_word_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='audio',
            new_name='url',
        ),
    ]
